# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"lognorm": "00_core.ipynb",
         "lognorm_columns": "00_core.ipynb",
         "filter_pdna": "00_core.ipynb",
         "calculate_lfcs": "00_core.ipynb",
         "get_condition": "00_core.ipynb",
         "average_replicate_lfcs": "00_core.ipynb",
         "group_pseudogenes": "00_core.ipynb",
         "average_gene_lfcs": "00_core.ipynb",
         "get_roc_aucs": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gpp-rnd.github.io/poola/"

git_url = "https://github.com/gpp-rnd/poola/tree/master/"

def custom_doc_links(name): return None
